// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/atf-redesign/HeroEn.tsx": () => import("../components/mockups/atf-redesign/HeroEn.tsx"),
  "./components/mockups/atf-redesign/HeroHr.tsx": () => import("../components/mockups/atf-redesign/HeroHr.tsx"),
  "./components/mockups/pdf-tiers/Basic.tsx": () => import("../components/mockups/pdf-tiers/Basic.tsx"),
  "./components/mockups/pdf-tiers/Free.tsx": () => import("../components/mockups/pdf-tiers/Free.tsx"),
  "./components/mockups/pdf-tiers/Pro.tsx": () => import("../components/mockups/pdf-tiers/Pro.tsx"),
  "./components/mockups/comparison-table/ClassicMatrix.tsx": () => import("../components/mockups/comparison-table/ClassicMatrix.tsx"),
  "./components/mockups/comparison-table/ProgressiveDepth.tsx": () => import("../components/mockups/comparison-table/ProgressiveDepth.tsx"),
  "./components/mockups/comparison-table/TierCardsHighlighted.tsx": () => import("../components/mockups/comparison-table/TierCardsHighlighted.tsx"),
  "./components/mockups/usp-cards/Ads.tsx": () => import("../components/mockups/usp-cards/Ads.tsx"),
  "./components/mockups/usp-cards/Ai.tsx": () => import("../components/mockups/usp-cards/Ai.tsx"),
  "./components/mockups/usp-cards/Fixes.tsx": () => import("../components/mockups/usp-cards/Fixes.tsx"),
  "./components/mockups/usp-cards/Seo.tsx": () => import("../components/mockups/usp-cards/Seo.tsx")
};
